CREATE TABLE IF NOT EXISTS person (
    `personName` VARCHAR(24) CHARACTER SET utf8,
    `personAge` INT,
    `personAddress` VARCHAR(9) CHARACTER SET utf8,
    `emailId` VARCHAR(22) CHARACTER SET utf8,
    `married` INT,
    `educationLevel` VARCHAR(7) CHARACTER SET utf8
);
INSERT INTO person VALUES
    ('Chanda Bhagat',43,'Mumbai','wagnerch@sbcglobal.net',0,'MSc.'),
    ('Jawahar Chadda',41,'Ahemdabad','skaufman@att.net',1,'Diploma'),
    ('Ramaeshwara Viswan',34,'Udaipur','pthomsen@comcast.net',0,'B.E.'),
    ('Bana Sinha',32,'Jaipur','frostman@sbcglobal.net',0,'HSC'),
    ('Viswarupa Dvivedi',20,'Amritsar','dwivedi.visw@bmail.com',1,'BBA'),
    ('Kusika Ahuja',46,'Jodhpur','schwaang@msn.com',0,'MSc.'),
    ('Vijya Gulati',49,'Pune','geekoid@msn.com',1,'Diploma'),
    ('Chand Poddar',21,'Bangalore','mleary@live.com',0,'B.E.'),
    ('Ranjan Sarkar',27,'Hyderabad','padme@gmail.com',0,'HSC'),
    ('Zohana Nayar',22,'Guwahati','ovprit@comcast.net',1,'BBA'),
    ('Neha Gupta',50,'Mumbai','larry@att.net',0,'BCA'),
    ('Aasiya Parachure',35,'Shillong','preneel@icloud.com',0,'MSc.'),
    ('Shruti Deshmukh',46,'Jaipur','heidrich@yahoo.com',1,'Diploma'),
    ('Satya Bajpeyi',33,'Amritsar','thomasj@mac.com',0,'B.E.'),
    ('Sarojini Kapadia',18,'Delhi','bader@att.net',0,'HSC'),
    ('Aaliya Dvivedi',21,'Jodhpur','avalon@icloud.com',1,'BBA'),
    ('Priya Nambiyar',49,'Pune','rddesign@yahoo.ca',0,'BCA'),
    ('Kanti Upalekar',30,'Bangalore','janusfury@comcast.net',0,'MSc.'),
    ('Jindan Sardar',19,'Hyderabad','subir@gmail.com',1,'Diploma'),
    ('Rajendra Ajagavakar',47,'Guwahati','mugwump@outlook.com',0,'B.E.'),
    ('Dasra Sinha',40,'Mumbai','karasik@live.com',0,'HSC'),
    ('Vikramaditya Adhya',17,'Shillong','dougj@me.com',1,'BBA'),
    ('Kusika Mirchandani',21,'Pune','agapow@msn.com',0,'BCA'),
    ('Dhuleep Dhebar',44,'Mumbai','yzheng@me.com',0,'MSc.'),
    ('Dhani Badakar',28,'Bangalore','jbuchana@yahoo.com',1,'Diploma'),
    ('Dayananda Malviya',25,'Hyderabad','stinson@mac.com',0,'B.E.'),
    ('Ramaeshwara Chipalunakar',36,'Mumbai','onestab@aol.com',0,'HSC'),
    ('Ayaan Talavalakar',36,'Udaipur','nasarius@yahoo.com',1,'BBA'),
    ('Vasishtha Gazdar',48,'Bangalore','thassine@att.net',0,'BCA'),
    ('Anushree Ajagavakar',24,'Hyderabad','vsprintf@gmail.com',0,'MSc.'),
    ('Durga Valimbe',47,'Shillong','heidrich@live.com',1,'Diploma'),
    ('Sonamoni Shrivastav',25,'Shillong','jbarta@optonline.net',0,'B.E.'),
    ('Mahamai Nambiyar',16,'Mumbai','openldap@sbcglobal.net',0,'HSC'),
    ('Rani Panja',24,'Guwahati','wainwrig@optonline.net',1,'BBA'),
    ('Vayu Nijasure',45,'Guwahati','jfinke@aol.com',0,'BCA'),
    ('Aahana Adhya',22,'Mumbai','fglock@sbcglobal.net',0,'MSc.'),
    ('Kunti Bagchi',37,'Guwahati','frederic@verizon.net',1,'Diploma'),
    ('Snigdha Pandey',18,'Udaipur','yumpy@hotmail.com',0,'B.E.'),
    ('Jaswant Raj',34,'Mumbai','meder@yahoo.ca',0,'HSC'),
    ('Sunder Bhatta',36,'Udaipur','johnh@live.com',1,'BBA'),
    ('Ramaeshwara Mahalana',31,'Udaipur','jaesenj@sbcglobal.net',0,'BCA'),
    ('Ravi Chaudhari',33,'Mumbai','nachbaur@hotmail.com',0,'MSc.'),
    ('Maha Valimbe',30,'Jaipur','brickbat@icloud.com',1,'Diploma'),
    ('Viswamitra Poddar',29,'Jodhpur','godeke@comcast.net',0,'B.E.'),
    ('Acarya Padhi',45,'Mumbai','netsfr@comcast.net',0,'HSC'),
    ('Dharya Kapil',19,'Jaipur','sbmrjbr@yahoo.ca',1,'BBA'),
    ('Aryabhata Bhavalakar',18,'Jodhpur','ninenine@gmail.com',0,'BCA'),
    ('Chatur Dayal',48,'Mumbai','cameron@yahoo.ca',0,'MSc.');
